version: '2'

services:
  web:
    build: .
    command: pumactl -F /portus/config/puma.rb start
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=docker.doodle.com
      - PORTUS_DB_HOST=db
      - PORTUS_DB_PASSWORD=portus
      - PORTUS_PUMA_HOST=0.0.0.0:80
      - PORTUS_PUMA_WORKERS=2
      - PORTUS_PUMA_MAX_THREADS=4
    volumes:
      - .:/portus
    ports:
      - 80:3000
    links:
      - db

  crono:
    image: portus_web
    entrypoint: bin/crono
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=docker.doodle.com
      - PORTUS_DB_HOST=db
      - PORTUS_DB_PASSWORD=portus
    volumes:
      - .:/portus
    links:
      - db

  db:
    image: library/mariadb:10.0.23
    environment:
      MYSQL_ROOT_PASSWORD: portus
  #
  # registry:
  #   image: library/registry:2.3.1
  #   environment:
  #     - REGISTRY_AUTH_TOKEN_REALM=http://192.168.88.194:3000/v2/token
  #     - REGISTRY_AUTH_TOKEN_SERVICE=192.168.88.194:5000
  #     - REGISTRY_AUTH_TOKEN_ISSUER=192.168.88.194
  #   volumes:
  #     - /registry_data
  #     - ./compose/registry/portus.crt:/etc/docker/registry/portus.crt:ro
  #     - ./compose/registry/config.yml:/etc/docker/registry/config.yml:ro
  #   ports:
  #     - 5000:5000
  #     - 5001:5001 # required to access debug service
  #   links:
  #     - web
