version: 0.1
storage:
  filesystem:
    rootdirectory: /registry_data
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
auth:
  token:
     realm: http://docker.doodle.com/v2/token
     service: docker.doodle.com:5000
     issuer: docker.doodle.com
     rootcertbundle: /etc/docker/registry/portus.crt
notifications:
  endpoints:
    - name: portus
      url: http://docker.doodle.com/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
